#define DYNAMIC_KEYMAP_LAYER_COUNT 8

#define LEADER_NO_TIMEOUT
#define LEADER_PER_KEY_TIMING
#define LEADER_TIMEOUT 300

#define DYNAMIC_MACRO_SIZE 256
#define DYNAMIC_MACRO_DELAY 50

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD

// mouse keys accelerated but allow momentary speed setting
#define MK_COMBINED

#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_SOLID_COLOR
#define RGB_MATRIX_DEFAULT_HUE 0
#define RGB_MATRIX_DEFAULT_SAT 255
#define RGB_MATRIX_DEFAULT_VAL RGB_MATRIX_MAXIMUM_BRIGHTNESS
#define RGB_MATRIX_DEFAULT_SPD 127

// inverted from previous config.h with "///"
// #    define RGB_MATRIX_KEYPRESSES
// #    define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#    undef RGB_MATRIX_KEYPRESSES
#    undef RGB_MATRIX_FRAMEBUFFER_EFFECTS

// #    define ENABLE_RGB_MATRIX_ALPHAS_MODS // does nothing
// #    define ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
// #    define ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
/// #    define ENABLE_RGB_MATRIX_BREATHING
#    undef ENABLE_RGB_MATRIX_BREATHING
// #    define ENABLE_RGB_MATRIX_BAND_SAT
// #    define ENABLE_RGB_MATRIX_BAND_VAL
// #    define ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
// #    define ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
// #    define ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT
/// #    define ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
/// #    define ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
/// #    define ENABLE_RGB_MATRIX_CYCLE_ALL
/// #    define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
/// #    define ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
/// #    define ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
/// #    define ENABLE_RGB_MATRIX_CYCLE_OUT_IN
/// #    define ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
/// #    define ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
/// #    define ENABLE_RGB_MATRIX_CYCLE_SPIRAL
/// #    define ENABLE_RGB_MATRIX_DUAL_BEACON
/// #    define ENABLE_RGB_MATRIX_RAINBOW_BEACON
#    undef ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
#    undef ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
#    undef ENABLE_RGB_MATRIX_CYCLE_ALL
#    undef ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#    undef ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#    undef ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
#    undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN
#    undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#    undef ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
#    undef ENABLE_RGB_MATRIX_CYCLE_SPIRAL
#    undef ENABLE_RGB_MATRIX_DUAL_BEACON
#    undef ENABLE_RGB_MATRIX_RAINBOW_BEACON

// #    define ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS
// #    define ENABLE_RGB_MATRIX_RAINDROPS
/// #    define ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#    undef ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
// #    define ENABLE_RGB_MATRIX_HUE_BREATHING
// #    define ENABLE_RGB_MATRIX_HUE_PENDULUM
// #    define ENABLE_RGB_MATRIX_HUE_WAVE
/// #    define ENABLE_RGB_MATRIX_PIXEL_RAIN
#    undef ENABLE_RGB_MATRIX_PIXEL_RAIN
// #    define ENABLE_RGB_MATRIX_PIXEL_FLOW
// #    define ENABLE_RGB_MATRIX_PIXEL_FRACTAL

/* enabled only if RGB_MATRIX_FRAMEBUFFER_EFFECTS is defined */
/// #    define ENABLE_RGB_MATRIX_TYPING_HEATMAP // cool
/// #    define ENABLE_RGB_MATRIX_DIGITAL_RAIN
#    undef ENABLE_RGB_MATRIX_TYPING_HEATMAP // cool
#    undef ENABLE_RGB_MATRIX_DIGITAL_RAIN

/*  enabled only of RGB_MATRIX_KEYPRESSES or RGB_MATRIX_KEYRELEASES is defined*/
/// #    define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE // black -> hue
#    undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE // black -> hue
// #    define ENABLE_RGB_MATRIX_SOLID_REACTIVE // current hue -> new hue
// #    define ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
// #    define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
// #    define ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
// #    define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
/// #    define ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
/// #    define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
/// #    define ENABLE_RGB_MATRIX_SPLASH
#    undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
#    undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
#    undef ENABLE_RGB_MATRIX_SPLASH
#    undef ENABLE_RGB_MATRIX_MULTISPLASH
/// #    define ENABLE_RGB_MATRIX_SOLID_SPLASH
#    undef ENABLE_RGB_MATRIX_SOLID_SPLASH
//#    define ENABLE_RGB_MATRIX_SOLID_MULTISPLASH
